title: Apprendendo
description: GitHub oficial de Apprendendo.blog
theme: jekyll-theme-architect

url: "https://apprendendo.github.io"
baseurl: "/.github"

include:
  - docs
  - profile

defaults:
  - scope:
      path: ""
    values:
      layout: default
