title: Apprendendo
description: GitHub oficial de Apprendendo.blog
# Tema escolhido
theme: jekyll-theme-architect

# Configuração de URLs para o subdomínio e subpasta
url: "https://apprendendo.github.io"
baseurl: "/"

# Garante que a pasta docs e seus arquivos sejam processados pelo Jekyll
include:
  - docs
  - profile
